#!/bin/bash
sbatch job-generic-usage-complete_5.sbatch Qwen2.5-72B-Instruct
sbatch job-generic-usage-complete_4.sbatch Qwen2.5-72B-Instruct
sbatch job-generic-usage-complete_3.sbatch Qwen2.5-72B-Instruct
sbatch job-generic-usage-complete_2.sbatch Qwen2.5-72B-Instruct
sbatch job-generic-usage-complete.sbatch Qwen2.5-72B-Instruct
sbatch job-generic-usage-complete_5.sbatch Llama-3.3-70B-Instruct
sbatch job-generic-usage-complete_4.sbatch Llama-3.3-70B-Instruct
sbatch job-generic-usage-complete_3.sbatch Llama-3.3-70B-Instruct
sbatch job-generic-usage-complete_2.sbatch Llama-3.3-70B-Instruct
sbatch job-generic-usage-complete.sbatch Llama-3.3-70B-Instruct

