#!/bin/bash
sbatch job-generic-usage-complete_5.sbatch Qwen2.5-7B-Instruct 
sbatch job-generic-usage-complete_4.sbatch Qwen2.5-7B-Instruct 
sbatch job-generic-usage-complete_3.sbatch Qwen2.5-7B-Instruct 
sbatch job-generic-usage-complete_2.sbatch Qwen2.5-7B-Instruct 
sbatch job-generic-usage-complete.sbatch Qwen2.5-7B-Instruct 
sbatch job-generic-usage-complete_5.sbatch Qwen2.5-14B-Instruct 
sbatch job-generic-usage-complete_4.sbatch Qwen2.5-14B-Instruct 
sbatch job-generic-usage-complete_3.sbatch Qwen2.5-14B-Instruct 
sbatch job-generic-usage-complete_2.sbatch Qwen2.5-14B-Instruct 
sbatch job-generic-usage-complete.sbatch Qwen2.5-14B-Instruct 
sbatch job-generic-usage-complete_5.sbatch Qwen2.5-32B-Instruct 
sbatch job-generic-usage-complete_4.sbatch Qwen2.5-32B-Instruct 
sbatch job-generic-usage-complete_3.sbatch Qwen2.5-32B-Instruct 
sbatch job-generic-usage-complete_2.sbatch Qwen2.5-32B-Instruct 
sbatch job-generic-usage-complete.sbatch Qwen2.5-32B-Instruct 
sbatch job-generic-usage-complete_5.sbatch Llama-3.1-8B-Instruct 
sbatch job-generic-usage-complete_4.sbatch Llama-3.1-8B-Instruct 
sbatch job-generic-usage-complete_3.sbatch Llama-3.1-8B-Instruct 
sbatch job-generic-usage-complete_2.sbatch Llama-3.1-8B-Instruct 
sbatch job-generic-usage-complete.sbatch Llama-3.1-8B-Instruct
sbatch job-generic-usage-complete_DeepSeek.sbatch DeepSeek
sbatch job-generic-usage-complete_DeepSeek_2.sbatch DeepSeek
sbatch job-generic-usage-complete_DeepSeek_3.sbatch DeepSeek
sbatch job-generic-usage-complete_DeepSeek_4.sbatch DeepSeek
sbatch job-generic-usage-complete_DeepSeek_5.sbatch DeepSeek

